runtime: go
api_version: go1
env_variables:
  HEIGHT: 500
  WIDTH: 500

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /static
  static_dir: static
- url: /.*
  script: _go_app

error_handlers:
  - file: /static/error.html

  - error_code: over_quota
    file: /static/over_quota.html